insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Sayre', 'Fittis', 25, 'sfittis0@buzzfeed.com', 'Mathematics');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Meghan', 'Provost', 40, 'mprovost1@java.com', 'Computer science');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Danna', 'de Zamora', 23, 'ddezamora2@kickstarter.com', 'Embedded systems');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Meghan', 'Hawkeridge', 35, 'nhawkeridge3@homestead.com', 'Mathematics');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Sula', 'Baitey', 38, 'sbaitey4@biglobe.ne.jp', 'Embedded systems');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Torr', 'McEnhill', 23, 'tmcenhill5@chron.com', 'Computer science');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Eadie', 'Gamell', 31, 'egamell6@wordpress.org', 'Mathematics');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Wheeler', 'Ilieve', 28, 'wilieve7@zimbio.com', 'Physics');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Nikolos', 'Daubeny', 25, 'ndaubeny8@barnesandnoble.com', 'Embedded systems');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Winn', 'D''Oyly', 31, 'wdoyly9@skype.com', 'Physics');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Delmar', 'Kennon', 24, 'dkennona@instagram.com', 'Computer science');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Donna', 'Farrington', 37, 'dfarringtonb@uiuc.edu', 'Computer science');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Ernesta', 'Lydster', 22, 'elydsterc@dedecms.com', 'Embedded systems');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Andrej', 'Glynne', 35, 'aglynned@ibm.com', 'Mathematics');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Baxter', 'Shafe', 19, 'bshafee@twitpic.com', 'Embedded systems');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Hatty', 'Moye', 40, 'hmoyef@mail.ru', 'Computer science');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Hildagard', 'Scurrell', 35, 'hscurrellg@mozilla.org', 'Embedded systems');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Clea', 'Quilty', 40, 'cquiltyh@nymag.com', 'Physics');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Laurens', 'Gudeman', 24, 'lgudemani@hud.gov', 'Embedded systems');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Nolie', 'Huxham', 37, 'nhuxhamj@soundcloud.com', 'Mathematics');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Reagan', 'Schaffler', 33, 'rschafflerk@mozilla.org', 'Computer science');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Travus', 'Westmoreland', 25, 'twestmorelandl@theatlantic.com', 'Computer science');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Benedikt', 'Jancso', 25, 'bjancsom@paginegialle.it', 'Embedded systems');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Suzann', 'Landman', 37, 'slandmann@dot.gov', 'Physics');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Lenka', 'Clitsome', 40, 'lclitsomeo@usatoday.com', 'Physics');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Herculie', 'Sommerfeld', 21, 'hsommerfeldp@sitemeter.com', 'Physics');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Dieter', 'Magnar', 26, 'dmagnarq@google.com.au', 'Embedded systems');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Bobbie', 'Caldroni', 32, 'bcaldronir@youku.com', 'Physics');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ( 'Claudine', 'Chardin', 31, 'cchardins@lulu.com', 'Embedded systems');
insert into STUDENT (FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values ('Kelby', 'Hawe', 26, 'khawet@friendfeed.com', 'Computer science');


insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Christean', 'Kuller', 33, 'ckuller0@wordpress.org', 'Physics');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Kat', 'Rolfi', 54, 'krolfi1@disqus.com', 'Embedded systems');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Kattie', 'Moryson', 32, 'kmoryson2@umn.edu', 'Mathematics');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Rosie', 'Cockland', 36, 'rcockland3@mit.edu', 'Mathematics');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Nomi', 'Rosenauer', 60, 'nrosenauer4@va.gov', 'Physics');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ('Peder', 'Bitchener', 20, 'pbitchener5@vkontakte.ru', 'Mathematics');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Merell', 'Gascoyne', 18, 'mgascoyne6@yellowbook.com', 'Embedded systems');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Mitchell', 'Paulat', 31, 'mpaulat7@clickbank.net', 'Embedded systems');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Carine', 'Rudkin', 27, 'crudkin8@sitemeter.com', 'Mathematics');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Bessie', 'Shevlan', 65, 'bshevlan9@gov.uk', 'Embedded systems');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Damon', 'Jaram', 51, 'djarama@ox.ac.uk', 'Computer science');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ('Peder', 'Jankiewicz', 53, 'pjankiewiczb@msn.com', 'Physics');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Ardelia', 'Adamov', 57, 'aadamovc@tumblr.com', 'Mathematics');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Ellsworth', 'Guyonneau', 45, 'eguyonneaud@seattletimes.com', 'Physics');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Cyrill', 'Terbrugge', 37, 'cterbruggee@ezinearticles.com', 'Embedded systems');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Genvieve', 'de Bullion', 40, 'gdebullionf@naver.com', 'Mathematics');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Theresina', 'Lusgdin', 37, 'tlusgding@com.com', 'Mathematics');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Midge', 'Knatt', 43, 'mknatth@gravatar.com', 'Embedded systems');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Annmarie', 'Lewsley', 30, 'alewsleyi@sfgate.com', 'Mathematics');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Ad', 'Skerman', 65, 'askermanj@phoca.cz', 'Mathematics');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Addie', 'Lorenzini', 41, 'alorenzinik@shop-pro.jp', 'Embedded systems');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Ariel', 'McVittie', 18, 'amcvittiel@statcounter.com', 'Mathematics');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Rochester', 'Draper', 63, 'rdraperm@tinypic.com', 'Physics');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Sarina', 'Steele', 38, 'ssteelen@examiner.com', 'Mathematics');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Briggs', 'Lardiner', 64, 'blardinero@uiuc.edu', 'Physics');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Cherye', 'Honatsch', 40, 'chonatschp@fc2.com', 'Physics');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ('Cathleen', 'M''Quhan', 33, 'cmquhanq@seesaa.net', 'Embedded systems');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ('Dannye', 'Deehan', 47, 'ddeehanr@dedecms.com', 'Embedded systems');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ('Khalil', 'Hambridge', 30, 'khambridges@ezinearticles.com', 'Embedded systems');
insert into TEACHER (FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values ( 'Minnie', 'Keats', 42, 'mkeatst@unc.edu', 'Mathematics');