insert into STUDENT (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values (1, 'Sayre', 'Fittis', 25, 'sfittis0@buzzfeed.com', 'Mathematics');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values (2, 'Meghan', 'Provost', 40, 'mprovost1@java.com', 'Computer science');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values (3, 'Danna', 'de Zamora', 23, 'ddezamora2@kickstarter.com', 'Embedded systems');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values (4, 'Meghan', 'Hawkeridge', 35, 'nhawkeridge3@homestead.com', 'Mathematics');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values (5, 'Sula', 'Baitey', 38, 'sbaitey4@biglobe.ne.jp', 'Embedded systems');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values (6, 'Torr', 'McEnhill', 23, 'tmcenhill5@chron.com', 'Computer science');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values (7, 'Eadie', 'Gamell', 31, 'egamell6@wordpress.org', 'Mathematics');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values (8, 'Wheeler', 'Ilieve', 28, 'wilieve7@zimbio.com', 'Physics');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values (9, 'Nikolos', 'Daubeny', 25, 'ndaubeny8@barnesandnoble.com', 'Embedded systems');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values (10, 'Winn', 'D''Oyly', 31, 'wdoyly9@skype.com', 'Physics');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values (11, 'Delmar', 'Kennon', 24, 'dkennona@instagram.com', 'Computer science');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values (12, 'Donna', 'Farrington', 37, 'dfarringtonb@uiuc.edu', 'Computer science');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values (13, 'Ernesta', 'Lydster', 22, 'elydsterc@dedecms.com', 'Embedded systems');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values (14, 'Andrej', 'Glynne', 35, 'aglynned@ibm.com', 'Mathematics');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values (15, 'Baxter', 'Shafe', 19, 'bshafee@twitpic.com', 'Embedded systems');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values (16, 'Hatty', 'Moye', 40, 'hmoyef@mail.ru', 'Computer science');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values (17, 'Hildagard', 'Scurrell', 35, 'hscurrellg@mozilla.org', 'Embedded systems');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values (18, 'Clea', 'Quilty', 40, 'cquiltyh@nymag.com', 'Physics');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values (19, 'Laurens', 'Gudeman', 24, 'lgudemani@hud.gov', 'Embedded systems');
insert into STUDENT (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, FIELD_OF_STUDY) values (20, 'Nolie', 'Huxham', 37, 'nhuxhamj@soundcloud.com', 'Mathematics');

insert into TEACHER (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values (1, 'Christean', 'Kuller', 33, 'ckuller0@wordpress.org', 'Physics');
insert into TEACHER (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values (2, 'Kat', 'Rolfi', 54, 'krolfi1@disqus.com', 'Embedded systems');
insert into TEACHER (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values (3, 'Kattie', 'Moryson', 32, 'kmoryson2@umn.edu', 'Mathematics');
insert into TEACHER (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values (4, 'Rosie', 'Cockland', 36, 'rcockland3@mit.edu', 'Mathematics');
insert into TEACHER (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values (5, 'Nomi', 'Rosenauer', 60, 'nrosenauer4@va.gov', 'Physics');
insert into TEACHER (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values (6, 'Peder', 'Bitchener', 20, 'pbitchener5@vkontakte.ru', 'Mathematics');
insert into TEACHER (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values (7, 'Merell', 'Gascoyne', 18, 'mgascoyne6@yellowbook.com', 'Embedded systems');
insert into TEACHER (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values (8, 'Mitchell', 'Paulat', 31, 'mpaulat7@clickbank.net', 'Embedded systems');
insert into TEACHER (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values (9, 'Carine', 'Rudkin', 27, 'crudkin8@sitemeter.com', 'Mathematics');
insert into TEACHER (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values (10, 'Bessie', 'Shevlan', 65, 'bshevlan9@gov.uk', 'Embedded systems');
insert into TEACHER (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values (11, 'Damon', 'Jaram', 51, 'djarama@ox.ac.uk', 'Computer science');
insert into TEACHER (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values (12, 'Peder', 'Jankiewicz', 53, 'pjankiewiczb@msn.com', 'Physics');
insert into TEACHER (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values (13, 'Ardelia', 'Adamov', 57, 'aadamovc@tumblr.com', 'Mathematics');
insert into TEACHER (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values (14, 'Ellsworth', 'Guyonneau', 45, 'eguyonneaud@seattletimes.com', 'Physics');
insert into TEACHER (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values (15, 'Cyrill', 'Terbrugge', 37, 'cterbruggee@ezinearticles.com', 'Embedded systems');
insert into TEACHER (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values (16, 'Genvieve', 'de Bullion', 40, 'gdebullionf@naver.com', 'Mathematics');
insert into TEACHER (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values (17, 'Theresina', 'Lusgdin', 37, 'tlusgding@com.com', 'Mathematics');
insert into TEACHER (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values (18, 'Midge', 'Knatt', 43, 'mknatth@gravatar.com', 'Embedded systems');
insert into TEACHER (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values (19, 'Annmarie', 'Lewsley', 30, 'alewsleyi@sfgate.com', 'Mathematics');
insert into TEACHER (ID, FIRST_NAME, LAST_NAME, AGE, MAIL, SUBJECT) values (20, 'Ad', 'Skerman', 65, 'askermanj@phoca.cz', 'Mathematics');